app = "accountabilabuddy"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "44000"

[[services]]
  internal_port = 44000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  # Optional health check hitting /healthz
  [[services.checks]]
    type = "http"
    interval = "15s"
    timeout = "2s"
    grace_period = "10s"
    method = "GET"
    path = "/healthz"
